"use client";

import { useQuery } from "@tanstack/react-query";
import { Activity, CircleAlert, Gauge, TimerReset } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { getGatewayHealth } from "@/lib/api";
import type { GatewayHealth } from "@/lib/types";
import { formatPercent, titleCase } from "@/lib/utils";

const trackedBanks = ["SBI", "HDFC", "ICICI", "Axis", "Kotak", "PNB"];
type PendingHealth = Omit<GatewayHealth, "state"> & { state: "unknown" };
export default function GatewayHealthPage() { const health = useQuery({ queryKey: ["gateway-health"], queryFn: getGatewayHealth, refetchInterval: 5000 }); const entries = health.data?.items ?? []; const openCount = entries.filter((item) => item.state === "open").length; const degradedCount = entries.filter((item) => item.state === "half_open").length; const displayEntries: Array<GatewayHealth | PendingHealth> = entries.length ? entries : trackedBanks.map((bank) => ({ bank, rail: "UPI", state: "unknown", success_rate: 0, technical_failure_rate: 0, business_decline_rate: 0, timeout_rate: 0, baseline_success_rate: 0, sample_size: 0, recommended_action: "AWAIT_TRAFFIC", retry_after_seconds: 0, confidence: "LOW" })); return <div className="mx-auto max-w-7xl space-y-6"><PageHeader eyebrow="Gateway Operations" title="Live gateway health" description="Sliding-window payment rail telemetry with circuit-breaker state."><StatusBadge value={health.data?.available ? "healthy" : "unknown"} /></PageHeader><section className="grid gap-4 md:grid-cols-3"><Overview icon={Activity} label="Active bank / rail pairs" value={entries.length.toString()} /><Overview icon={CircleAlert} label="Open circuits" value={openCount.toString()} tone="rose" /><Overview icon={Gauge} label="Degraded circuits" value={degradedCount.toString()} tone="amber" /></section>{!health.data?.available && !health.isLoading && <Card><CardContent><p className="text-sm text-zinc-500">Redis telemetry is unavailable. Start Redis and inject a batch or outage to populate live gateway health.</p></CardContent></Card>}<section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{health.isLoading ? Array.from({ length: 6 }).map((_, index) => <Card key={index}><CardContent><Skeleton className="h-40" /></CardContent></Card>) : displayEntries.map((item, index) => <HealthCard item={item} key={`${item.bank}-${item.rail}-${index}`} />)}</section></div>; }
function Overview({ icon: Icon, label, value, tone = "teal" }: { icon: typeof Activity; label: string; value: string; tone?: "teal" | "amber" | "rose" }) { const colors = { teal: "text-teal-700 dark:text-teal-400", amber: "text-amber-700 dark:text-amber-400", rose: "text-rose-700 dark:text-rose-400" }; return <Card><CardContent className="flex items-center justify-between"><div><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div><Icon className={colors[tone]} size={20} /></CardContent></Card>; }
function HealthCard({ item }: { item: GatewayHealth | PendingHealth }) { const progress = Math.max(item.sample_size ? item.success_rate * 100 : 3, 3); const color = item.state === "open" ? "bg-rose-500" : item.state === "half_open" ? "bg-amber-400" : item.state === "closed" ? "bg-emerald-500" : "bg-zinc-300 dark:bg-zinc-700"; return <Card><CardHeader className="flex flex-row items-center justify-between"><div><h2 className="font-semibold">{item.bank}</h2><p className="mt-1 text-xs uppercase tracking-wide text-zinc-500">{item.rail}</p></div><StatusBadge value={item.state} /></CardHeader><CardContent className="space-y-4"><div><div className="flex justify-between text-xs text-zinc-500"><span>Success rate</span><span>{item.sample_size ? formatPercent(item.success_rate) : "Awaiting traffic"}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800"><div className={`h-full rounded-full ${color}`} style={{ width: `${progress}%` }} /></div></div><div className="grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-zinc-500">Technical failures</p><p className="mt-1 font-semibold">{formatPercent(item.technical_failure_rate)}</p></div><div><p className="text-xs text-zinc-500">Timeouts</p><p className="mt-1 font-semibold">{formatPercent(item.timeout_rate)}</p></div><div><p className="text-xs text-zinc-500">Sample size</p><p className="mt-1 font-semibold">{item.sample_size} attempts</p></div><div><p className="text-xs text-zinc-500">Recommended action</p><p className="mt-1 font-semibold">{titleCase(item.recommended_action)}</p></div></div>{item.retry_after_seconds > 0 && <div className="flex items-center gap-2 border-t border-zinc-100 pt-3 text-xs text-zinc-500 dark:border-zinc-800"><TimerReset size={14} /> Retry after {Math.ceil(item.retry_after_seconds / 60)} min</div>}</CardContent></Card>; }
